version: '3.8'

services:
  api:
    build: .
    container_name: llm-outfit-api
    ports:
      - "6020:6020"
    environment:
      # Only variables actually used by this server (config.py)
      # Base & server
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=${DEBUG:-False}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LLM_API_HOST=${LLM_API_HOST:-0.0.0.0}
      - LLM_API_PORT=${LLM_API_PORT:-6020}
      - DATABASE_URL=${DATABASE_URL}

      # LLM / Claude
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME:-claude-3-haiku-20240307}
      - LLM_MAX_TOKENS=${LLM_MAX_TOKENS:-1000}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.7}

      # Redis (host:port:db)
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DB=${REDIS_DB:-0}

      # AWS + S3 (project convention)
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION:-ap-northeast-2}
      - S3_COMBINATION_BUCKET_NAME=${S3_COMBINATION_BUCKET_NAME:-thefirsttake-combination}
      - S3_COMBINATION_BUCKET_IMAGE_PREFIX=${S3_COMBINATION_BUCKET_IMAGE_PREFIX:-image}
      - S3_COMBINATION_BUCKET_JSON_PREFIX=${S3_COMBINATION_BUCKET_JSON_PREFIX:-json}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6020/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - thefirsttake-network

networks:
  thefirsttake-network:
    driver: bridge
